resolver: lts-7.14

packages:
- .
- location:
    git: https://www.github.com/soenkehahn/wai-make-assets
    commit: c72a924
  extra-dep: true
# - location:
#     git: https://www.github.com/mattjbray/elm-export
#     commit: d995e32482f9704efb5d7d08568b56c518f01bd0
#   extra-dep: True
- location:
    git: https://www.github.com/mattjbray/servant-elm
    commit: 5d9bbcd9fcb6e1bdc0f3398cb95147e621d97837
  extra-dep: True

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
- elm-export-0.5.0.2
- time-1.5.0.1
- heroku-persistent-0.2.0
- heroku-0.1.2.3
- servant-auth-0.2.1.0
- servant-auth-server-0.2.1.0
- jose-0.5.0.2
